spring:
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true

server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  prefix: /api
  routes:
    multiplexmovieservice: /movtiplex/**
    multiplexregistrationservice: /auth/**
  ignored-services: '*'
